import { createStyles } from 'antd-style';

export const useProjectPageStyles = createStyles(({ token }) => ({
  page: {
    display: 'flex',
    flexDirection: 'column',
    gap: 18,
  },
  searchCard: {
    borderRadius: 12,
    border: `1px solid ${token.colorBorderSecondary}`,
    background: token.colorBgContainer,
    boxShadow: token.boxShadowTertiary,
    '.ant-card-body': {
      padding: '18px 20px',
    },
  },
  searchGrid: {
    display: 'grid',
    gridTemplateColumns: '1.2fr 1fr auto',
    gap: 16,
    alignItems: 'end',
    '@media (max-width: 1280px)': {
      gridTemplateColumns: 'repeat(2, 1fr)',
    },
    '@media (max-width: 640px)': {
      gridTemplateColumns: '1fr',
    },
  },
  searchField: {
    display: 'flex',
    flexDirection: 'column',
    gap: 6,
    minWidth: 0,
  },
  searchLabel: {
    fontSize: 13,
    color: token.colorTextSecondary,
    whiteSpace: 'nowrap',
  },
  searchActions: {
    display: 'flex',
    gap: 10,
    justifyContent: 'flex-end',
  },
  metricsRow: {
    marginBottom: 0,
  },
  metricCard: {
    borderRadius: 16,
    border: `1px solid ${token.colorBorderSecondary}`,
    boxShadow: token.boxShadowTertiary,
    height: '100%',
    '.ant-card-body': {
      padding: 20,
      display: 'flex',
      alignItems: 'center',
      gap: 14,
    },
  },
  metricIcon: {
    width: 48,
    height: 48,
    borderRadius: 14,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 22,
    flexShrink: 0,
  },
  metricIconBlue: {
    background: token.colorPrimaryBg,
    color: token.colorPrimary,
  },
  metricIconGreen: {
    background: token.colorSuccessBg,
    color: token.colorSuccess,
  },
  metricIconOrange: {
    background: token.colorWarningBg,
    color: token.colorWarning,
  },
  metricIconPurple: {
    background: token.colorInfoBg,
    color: token.colorInfo,
  },
  metricIconRed: {
    background: token.colorErrorBg,
    color: token.colorError,
  },
  metricName: { fontSize: 13, color: token.colorTextSecondary },
  metricValue: {
    fontSize: 26,
    fontWeight: 800,
    marginTop: 4,
    color: token.colorText,
    fontVariantNumeric: 'tabular-nums',
  },
  listCard: {
    borderRadius: 12,
    border: `1px solid ${token.colorBorderSecondary}`,
    background: token.colorBgContainer,
    boxShadow: token.boxShadowTertiary,
    '.ant-card-body': {
      padding: 16,
    },
  },
  panelHead: {
    display: 'flex',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 10,
    marginBottom: 12,
  },
  panelHeadLeft: {
    display: 'flex',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: 22,
  },
  panelTitle: {
    margin: 0,
    fontSize: 15,
    fontWeight: 700,
    color: token.colorText,
  },
  statusTabs: {
    marginBottom: 0,
    '.ant-tabs-nav': { marginBottom: 12 },
    '.ant-tabs-tab': { padding: '0 0 6px', fontSize: 13 },
  },
  panelTools: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    flexWrap: 'wrap',
  },
  projectGrid: {
    marginTop: 0,
  },
  projectCard: {
    height: '100%',
    boxSizing: 'border-box',
    borderRadius: 12,
    background: token.colorBgContainer,
    border: `1px solid ${token.colorBorder}`,
    boxShadow: token.boxShadowTertiary,
    padding: '12px 12px 10px',
    display: 'flex',
    flexDirection: 'column',
    transition:
      'transform 0.16s ease, box-shadow 0.16s ease, border-color 0.16s ease',
    '&:hover': {
      transform: 'translateY(-2px)',
      borderColor: token.colorPrimaryBorder,
      boxShadow: token.boxShadowSecondary,
    },
  },
  cardTop: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 10,
  },
  projectTitle: {
    display: 'flex',
    gap: 8,
    alignItems: 'center',
    minWidth: 0,
    flex: 1,
  },
  projectIcon: {
    width: 36,
    height: 36,
    borderRadius: 10,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontWeight: 800,
    fontSize: 13,
    flexShrink: 0,
    background: token.colorFillAlter,
  },
  titleText: {
    minWidth: 0,
    flex: 1,
  },
  projectName: {
    fontWeight: 700,
    fontSize: 14,
    marginBottom: 4,
    color: token.colorText,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  tags: {
    display: 'flex',
    gap: 4,
    flexWrap: 'wrap',
  },
  tag: {
    fontSize: 11,
    padding: '1px 6px',
    borderRadius: 999,
    fontWeight: 600,
    lineHeight: '16px',
  },
  tag_ok: {
    color: token.colorSuccess,
    background: token.colorSuccessBg,
  },
  tag_warn: {
    color: token.colorWarning,
    background: token.colorWarningBg,
  },
  tag_pending: {
    color: token.colorWarning,
    background: token.colorWarningBg,
  },
  tag_path: {
    color: token.colorPrimary,
    background: token.colorPrimaryBg,
  },
  moreBtn: {
    border: 'none',
    background: 'transparent',
    color: token.colorTextQuaternary,
    fontSize: 18,
    lineHeight: 1,
    cursor: 'pointer',
    padding: 0,
    flexShrink: 0,
    '&:hover': {
      color: token.colorTextSecondary,
    },
  },
  dangerText: {
    color: token.colorError,
  },
  infoRow: {
    display: 'grid',
    gridTemplateColumns: '1fr 72px',
    gap: 8,
    marginBottom: 8,
    fontSize: 12,
  },
  infoCell: { minWidth: 0 },
  infoCellBranch: { minWidth: 0 },
  infoLabel: {
    color: token.colorTextSecondary,
    marginBottom: 2,
    fontSize: 11,
  },
  infoValue: {
    color: token.colorText,
    wordBreak: 'break-all',
    fontSize: 12,
    lineHeight: 1.35,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    display: '-webkit-box',
    WebkitLineClamp: 1,
    WebkitBoxOrient: 'vertical',
  },
  riskBox: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, 1fr)',
    background: token.colorFillAlter,
    borderRadius: 8,
    padding: '8px 6px',
    marginBottom: 8,
    border: `1px solid ${token.colorBorderSecondary}`,
  },
  riskItem: {
    paddingLeft: 6,
    '&:not(:last-child)': {
      borderRight: `1px solid ${token.colorBorderSecondary}`,
    },
  },
  riskLabel: {
    fontSize: 11,
    color: token.colorTextSecondary,
    whiteSpace: 'nowrap',
  },
  riskValue: {
    fontSize: 14,
    fontWeight: 800,
    marginTop: 2,
    color: token.colorText,
    fontVariantNumeric: 'tabular-nums',
  },
  riskValueDanger: {
    fontSize: 14,
    fontWeight: 800,
    marginTop: 2,
    color: token.colorError,
    fontVariantNumeric: 'tabular-nums',
  },
  codeMeta: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, 1fr)',
    gap: 6,
    marginBottom: 8,
  },
  metaItem: {
    border: `1px solid ${token.colorBorderSecondary}`,
    borderRadius: 8,
    padding: '6px 8px',
    background: token.colorFillQuaternary,
  },
  metaTitle: {
    color: token.colorTextSecondary,
    fontSize: 11,
    marginBottom: 2,
    lineHeight: 1.2,
  },
  metaValue: {
    fontWeight: 700,
    fontSize: 12,
    color: token.colorText,
    fontVariantNumeric: 'tabular-nums',
  },
  langSection: {
    marginBottom: 0,
    paddingBottom: 8,
    borderBottom: `1px solid ${token.colorBorderSecondary}`,
  },
  langTitle: {
    color: token.colorTextSecondary,
    fontSize: 11,
    marginBottom: 4,
  },
  langBarEmpty: { fontSize: 11, color: token.colorTextQuaternary },
  langBarTrack: {
    height: 6,
    display: 'flex',
    overflow: 'hidden',
    borderRadius: 999,
    background: token.colorFillSecondary,
    marginBottom: 6,
  },
  langBarSegment: {
    display: 'block',
    height: '100%',
    minWidth: 2,
  },
  langList: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '4px 10px',
    fontSize: 11,
    color: token.colorTextSecondary,
    lineHeight: 1.3,
  },
  langListItem: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 2,
  },
  langDot: {
    display: 'inline-block',
    width: 6,
    height: 6,
    borderRadius: '50%',
    marginRight: 4,
    flexShrink: 0,
  },
  langTooltip: { display: 'flex', flexDirection: 'column', gap: 4 },
  langTooltipRow: { display: 'flex', alignItems: 'center', gap: 6 },
  cardFooter: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingTop: 8,
    gap: 6,
  },
  footerScan: {
    color: token.colorTextSecondary,
    fontSize: 11,
    flex: 1,
    minWidth: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  linkBtn: {
    height: 26,
    padding: '0 10px',
    border: `1px solid ${token.colorBorder}`,
    borderRadius: 6,
    background: token.colorBgContainer,
    color: token.colorPrimary,
    fontWeight: 600,
    fontSize: 12,
    boxShadow: 'none',
    flexShrink: 0,
    '&:hover': {
      color: token.colorPrimary,
      borderColor: token.colorPrimary,
      background: token.colorPrimaryBg,
    },
  },
  listRow: {
    marginBottom: 16,
  },
  emptyWrap: { padding: '48px 0' },
  paginationWrap: {
    marginTop: 24,
    display: 'flex',
    justifyContent: 'flex-end',
  },
}));
