# -*- coding: utf-8 -*-
"""证据点定义 —— 整合自 gbt-codeagent。"""

from typing import Dict, List

EVIDENCE_POINTS: Dict[str, List[str]] = {
    "CMD": [
        "EVID_CMD_EXEC_POINT",
        "EVID_CMD_COMMAND_STRING_CONSTRUCTION",
        "EVID_CMD_USER_PARAM_TO_CMD_FRAGMENT",
    ],
    "SQL": [
        "EVID_SQL_EXEC_POINT",
        "EVID_SQL_STRING_CONSTRUCTION",
        "EVID_SQL_USER_PARAM_TO_SQL_FRAGMENT",
    ],
    "NOSQL": [
        "EVID_NOSQL_QUERY_CONSTRUCTION",
        "EVID_NOSQL_USER_INPUT_INTO_QUERY_STRUCTURE",
        "EVID_NOSQL_OPERATOR_INJECTION_FIELDS",
    ],
    "LDAP": [
        "EVID_LDAP_EXEC_POINT",
        "EVID_LDAP_FILTER_STRING_CONSTRUCTION",
        "EVID_LDAP_USER_PARAM_TO_FILTER_FRAGMENT",
    ],
    "EXPR": [
        "EVID_EXPR_EVAL_ENTRY",
        "EVID_EXPR_EXPR_CONTROL",
        "EVID_EXPR_EXEC_CHAIN_ENTRY",
    ],
    "FILE": [
        "EVID_FILE_WRAPPER_PREFIX",
        "EVID_FILE_RESOLVED_TARGET",
        "EVID_FILE_INCLUDE_REQUIRE_EXEC_BOUNDARY",
    ],
    "WRITE": [
        "EVID_WRITE_WRITE_CALLSITE",
        "EVID_WRITE_DESTPATH_JOIN_AND_NORMALIZATION",
        "EVID_WRITE_DESTPATH_RESOLVED_TARGET",
        "EVID_WRITE_CONTENT_SOURCE_INTO_WRITE",
        "EVID_WRITE_TRUNCATE_OR_OVERWRITE_MODE",
        "EVID_WRITE_EXECUTION_ACCESSIBILITY_PROOF",
    ],
    "UPLOAD": [
        "EVID_UPLOAD_DESTPATH",
        "EVID_UPLOAD_FILENAME_EXTENSION_PARSING_SANITIZE",
        "EVID_UPLOAD_ACCESSIBILITY_PROOF",
        "EVID_UPLOAD_EXEC_DISABLE_STRATEGY",
    ],
    "ARCHIVE": [
        "EVID_ARCHIVE_EXTRACT_CALLSITE",
        "EVID_ARCHIVE_ENTRY_NAME_SOURCE",
        "EVID_ARCHIVE_ENTRY_SANITIZATION",
        "EVID_ARCHIVE_EXTRACT_BASE_DIR",
        "EVID_ARCHIVE_FINAL_TARGET",
    ],
    "SSRF": [
        "EVID_SSRF_URL_NORMALIZATION",
        "EVID_SSRF_FINAL_URL_HOST_PORT",
        "EVID_SSRF_FINAL_REDIRECT_URL",
        "EVID_SSRF_DNSIP_AND_INNER_BLOCK",
    ],
    "XSS": [
        "EVID_XSS_OUTPUT_POINT",
        "EVID_XSS_USER_INPUT_INTO_OUTPUT",
        "EVID_XSS_ESCAPE_OR_RAW_CONTROL",
    ],
    "REDIR": [
        "EVID_REDIR_OUTPUT_POINT",
        "EVID_REDIR_DEST_SOURCE_MAPPING",
        "EVID_REDIR_DEST_VALIDATION_NORMALIZATION",
    ],
    "CRLF": [
        "EVID_CRLF_OUTPUT_POINT",
        "EVID_CRLF_USER_INPUT_INTO_HEADER_COOKIE",
        "EVID_CRLF_CONTROL_CHAR_FILTERING_ENCODING",
    ],
    "XXE": [
        "EVID_XXE_PARSER_CALL",
        "EVID_XXE_INPUT_SOURCE",
        "EVID_XXE_ENTITY_DOCTYPE_SAFETY_AND_ECHO",
    ],
    "DESER": [
        "EVID_DESER_CALLSITE",
        "EVID_DESER_INPUT_SOURCE",
        "EVID_DESER_OBJECT_TYPE_MAGIC_TRIGGER_CHAIN",
    ],
    "TPL": [
        "EVID_TPL_ENGINE_RENDER_OR_PARSE_ENTRY",
        "EVID_TPL_TEMPLATE_OR_EXPR_CONTROL",
        "EVID_TPL_EXEC_CHAIN_ENTRY",
    ],
    "AUTH": [
        "EVID_AUTH_PATH_PROTECTED_MATCH",
        "EVID_AUTH_TOKEN_DECODE_JUDGMENT",
        "EVID_AUTH_PERMISSION_CHECK_EXEC",
        "EVID_AUTH_IDOR_OWNERSHIP_CONDITION",
    ],
    "CSRF": [
        "EVID_CSRF_STATE_CHANGE_HANDLER_EXEC",
        "EVID_CSRF_TOKEN_SOURCE",
        "EVID_CSRF_TOKEN_RECEIVE",
        "EVID_CSRF_TOKEN_VERIFY",
        "EVID_CSRF_BYPASS_BRANCH",
    ],
    "SESS": [
        "EVID_SESS_SESSION_INIT_REGEN",
        "EVID_SESS_COOKIE_FLAGS",
        "EVID_SESS_JWT_VERIFY_CLAIMS",
        "EVID_SESS_LOGOUT_CLEAR",
    ],
    "CFG": [
        "EVID_CFG_CONFIG_LOCATION",
        "EVID_CFG_RUNTIME_SETTING_CODE",
        "EVID_CFG_IMPACT_ASSOCIATION",
        "EVID_CFG_SECURITY_SWITCH_EVIDENCE",
    ],
}
